//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdCommand.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BirdCommand.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirdDown {
            get {
                object obj = ResourceManager.GetObject("BirdDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirdLeft {
            get {
                object obj = ResourceManager.GetObject("BirdLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirdRight {
            get {
                object obj = ResourceManager.GetObject("BirdRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirdUp {
            get {
                object obj = ResourceManager.GetObject("BirdUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Empty {
            get {
                object obj = ResourceManager.GetObject("Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass {
            get {
                object obj = ResourceManager.GetObject("Glass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HalfStone {
            get {
                object obj = ResourceManager.GetObject("HalfStone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HalfWood {
            get {
                object obj = ResourceManager.GetObject("HalfWood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wo-Wo-Wo-Wo-Wo-Wo-Wo-Wo
        ///Wo-Wo-Wo-St-Wo-St-Wo-Wo
        ///Wo-Wo-HW-Bi-Gl-Wo-Wo-HW
        ///Wo-Wo-St-Em-HW-Wo-Wo-Wo
        ///Wo-HW-HW-Pi-HW-Wo-Wo-Wo
        ///Wo-Wo-Wo-St-Wo-Wo-Wo-Wo
        ///Wo-Wo-Gl-St-Wo-Wo-Wo-HS
        ///Wo-Wo-Wo-St-Wo-HW-HS-Wo.
        /// </summary>
        internal static string hoc1 {
            get {
                return ResourceManager.GetString("hoc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wo-Wo-St-Wo-Wo-Wo-St-Wo
        ///Wo-Wo-Wo-Wo-Wo-Wo-Wo-Wo
        ///Wo-Wo-Wo-Wo-Wo-Wo-Wo-Wo
        ///HW-Wo-HW-Gl-HS-St-Wo-Wo
        ///Wo-Gl-BR-Em-Em-Pi-HS-Wo
        ///Wo-HW-St-HS-St-St-Wo-Wo
        ///Wo-Wo-Wo-HW-Wo-Wo-Wo-Wo
        ///Wo-Wo-Wo-Wo-Wo-Wo-Wo-Wo.
        /// </summary>
        internal static string hoc2 {
            get {
                return ResourceManager.GetString("hoc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wo-Wo-Wo-HW-Wo-Wo-HS-Wo
        ///Wo-Wo-Wo-Wo-HS-St-Wo-Wo
        ///Wo-HS-HW-Wo-Tn-St-Wo-St
        ///Wo-HW-BR-Em-Em-St-Gl-Wo
        ///St-Gl-Tn-Wo-Pi-HS-Wo-Wo
        ///Wo-St-St-Wo-St-Wo-Wo-Wo
        ///St-Wo-Wo-Wo-Wo-Wo-Wo-Wo
        ///Wo-Wo-Wo-Wo-HS-Wo-Wo-Wo.
        /// </summary>
        internal static string hoc3 {
            get {
                return ResourceManager.GetString("hoc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pig {
            get {
                object obj = ResourceManager.GetObject("Pig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rule {
            get {
                object obj = ResourceManager.GetObject("rule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rule_start {
            get {
                object obj = ResourceManager.GetObject("rule_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run_button {
            get {
                object obj = ResourceManager.GetObject("run_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snap {
            get {
                object obj = ResourceManager.GetObject("snap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stone {
            get {
                object obj = ResourceManager.GetObject("Stone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TNT {
            get {
                object obj = ResourceManager.GetObject("TNT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wood {
            get {
                object obj = ResourceManager.GetObject("Wood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
